### ISSUE TITLE
Incorrect example used in 'Using Selenium to write tests' section

### ISSUE THREAD

**Issue by JamesBrowning1991** [baijum/selenium-python#38]
It took me a little while to work out why the unittest example wasn't working yet the 'Simple Usage' example was.  It's quite simple really but I thought I should let you know.

"
def test_search_in_python_org(self):
        driver = self.driver
        driver.get("http://www.python.org")
        self.assertIn("Python", driver.title)
        elem = driver.find_element_by_name("q")
        elem.send_keys("pycon")
        assert "No results found." not in driver.page_source
        elem.send_keys(Keys.RETURN)
"

This is your 'test_search_in_python_org' test in the example.  The 'elem.send_keys(Keys.RETURN)' comes after the ' assert "No results found." not in driver.page_source'. It should come before otherwise the test will always pass.

**Comment by baijum** [comment]
Thanks for the report.  This is fixed now.
