### ISSUE TITLE
selenium PhantomJS driver cannot get "https://vid.me/" url

### ISSUE THREAD

**Issue by kushalmangtani** [baijum/selenium-python#52]
Not sure, why this is happenning. However, felt obligated to report an issue about it!
Look at [4] below, you will notice that 'https://vid.me/' is not loaded correctly by selenium

$ pip freeze | grep selenium
selenium==2.42.1

```
In [1]: from selenium import webdriver

In [2]: driver = webdriver.PhantomJS()

In [3]: driver.get("https://vid.me/")

In [4]: driver.current_url
Out[4]: u'about:blank'

In [5]: driver.get("https://facebook.com/")

In [6]: driver.current_url
Out[6]: u'https://www.facebook.com/?_rdr=p'
```

**Comment by baijum** [comment]
@kushalmangtani This issue tracker is for the book not the Selenium project.

**Comment by kushalmangtani** [comment]
@baijum - thanks for replying back. I'm not sure what do you mean by the book. could you elaborate ?

**Comment by baijum** [comment]
@kushalmangtani Sorry, I mean the "documentation" : https://selenium-python.readthedocs.org/
