### ISSUE TITLE
Response from command executor does not always contain a field named message

### ISSUE THREAD

**Issue by metareven** [baijum/selenium-python#59]
Whenever clicking an element fails because another element is blocking it, you get no proper error message as the error handler crashes during execution of the following code:
```python
message=value["value"]["message"]
```
This is because ``` value["value"] ``` is a string and not a map.

Made the following change to check_response in errorhandler.py myself to get it to work again, but I assume you might want to handle it in another way :
```python
if value_json and isinstance(value_json, basestring):
                import json
                try:
                  value = json.loads(value_json)
                  status = value.get('error', None)
                  if status is None:
                      status = value["status"]
                      #message = value["value"]["message"]
                      val = value["value"]##
                      if isinstance(val,basestring):##
                          message = value["value"]##
                      else:##
                          message = value["value"]["message"]##
                  else:
                      message = value.get('message', None)
                except ValueError:
                  pass
```
It seems errors coming from the command executor sometimes contain a field name message in the value field, but some times it just contains a string with the error message directly

**Comment by baijum** [comment]
@metareven Please report this to selenium project: https://github.com/SeleniumHQ/selenium/issues
