### ISSUE TITLE
Docs: getting started page contains the same heading twice

### ISSUE THREAD

**Issue by guettli** [baijum/selenium-python#62]
http://selenium-python.readthedocs.org/getting-started.html

on above page the heading "Walk through of the example" exists twice.

Maybe you want it that way. At least for my eyes it looks a bit strange.

**Comment by baijum** [comment]
This is fixed in commit 66fc30db9c62afcd0a1b5997ef103e31864d2111

**Comment by baijum** [comment]
@guettli Thanks!
