### ISSUE TITLE
Docs: check for http status_code 200 after elem.send_keys(Keys.RETURN)

### ISSUE THREAD

**Issue by guettli** [baijum/selenium-python#64]
This snippet is from the docs:

```
elem.send_keys(Keys.RETURN)
assert "No results found." not in driver.page_source
```

I would like to check for a http status_code of 200 after the page reload.

At least that is what I have been doing before with the django test client.

**Comment by baijum** [comment]
WebDriver  doesn't have API to get status code.
Ref: https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/141
