### ISSUE TITLE
Can I translate this docs and republish it

### ISSUE THREAD

**Issue by delongw** [baijum/selenium-python#67]
I want to translate to Chinese and publish it for Chinese coder

**Comment by baijum** [comment]
@delongw Thanks for your interest to translate this document! Yes, you can do that.

This document use "Creative Commons Attribution-ShareAlike 4.0 International License."
http://creativecommons.org/licenses/by-sa/4.0/

So, please provide a link to original document: https://selenium-python.readthedocs.io/

All the best!
